### ISSUE TITLE
Continuing development

### ISSUE THREAD

**Issue by jlaumon** [alextretyak/ltalloc#1]
Hello!

Am I correct in assuming you are the original author of ltalloc?

There is a another repo with a few changes to ltalloc over there: https://github.com/r-lyeh-archived/ltalloc

Are you interested in getting pull requests and/or getting involved with future development of the allocator? I opened [an issue in the other repo](https://github.com/r-lyeh-archived/ltalloc/issues/17) because I would like to make some small changes to ltalloc, but I would love to have you opinion.

PS: thanks a lot for ltalloc, it's great!

**Comment by alextretyak** [comment]
Hi.

​​
> Am I correct in assuming you are the original author of ltalloc?


Yes, I am.

​​
> There is a another repo with a few changes to ltalloc over there:
> https://github.com/r-lyeh-archived/ltalloc


I know about it, and it seems it is the only meaningful attempt of
improving the allocator in whole WWW.

​ Are you interested in getting pull requests and/or getting involved with
> future development of the allocator? ​
>
>
No, I am not. The thing is ltalloc is not so great for real applications,
like DB engines or web servers. In general it behaves worse than other
memory allocators, like Hoard. And as I am not interested in becoming a
memory allocation expert, I decided to drop its development.


2018-07-08 19:31 GMT+10:00 jeremy <notifications@github.com>:

**Comment by jlaumon** [comment]
Thanks for the fast answer!

ltalloc may not be the best allocator in the world, but it's one file and it has no dependencies, which can be convenient (at least in my job, where I sometimes work on platforms that don't provide a decent default malloc implementation (sadly)). And ltalloc is a pretty good allocator compared to the others in this category.

I understand that you don't want to continue its development, but just know that there are people that still find it useful and thank you for that!

**Comment by r-lyeh** [comment]
hey guys, thanks for the heads up. @alextretyak i personally think you did a great job on the allocator :) i will keep maintaining PRs in that fork unless you want to merge some. I'll add a link to this repo as well in the README. regards!
